# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15dce97b283aa4cbdffa2e967b33e3cfdc8ee7f4ec1740a4611538f4604a5875a588835a3d6fba564907b23d072adbcb40f4301dd290a5fd3428a2aade688232

test:
  secret_key_base: a21aff28074bf2538f9dfe6645c4a7ec1c460546477d739cba9aa4011f7c76af53c885f211b869c49f29829dbb75901875aa2e5062f1a98c5622e8de149ce7e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
